(function($){
  var site = {}

  /**
   * Function to validate form
   * @return true or false if not valid.
   */
  function validateForm() {
    var result = true;
    $('label.required + input[type="text"]').each(function() {
      if ($(this).val() == '') {
        $(this).prev().addClass('error');
        result = false;
      }
      else {
        $(this).prev().removeClass('error');
      }
    });
    return result;
  }

  $('#submit').on('click', function(e) {
    e.preventDefault();
    var validate = validateForm();
    if (validate) {
      // Now we need to check values and start adding them to a json.
      var site_name = $('#site_name').val();
      site.name = site_name;
      description = 'This role was generated by the vampd generator';
      site.chef_type = 'role';
      site.json_class = 'Chef::Role';
      site.default_attributes = {};
      site.override_attributes = {
        drupal: {
          sites: {
          }
        }
      };
      site.override_attributes.drupal.sites[site_name] = {};
      site.override_attributes.drupal.sites[site_name].active = true;
      // Add the actions
      var actions = [];
      $('#actions input').each(function(i){
        if ($(this).is(':checked')) {
          actions[i] = $(this).val();
        }
      });
      site.override_attributes.drupal.sites[site_name].actions = actions;
      // Check the docroot
      var docroot = '';
      var docroot_before = '';
      if ($('#docroot_bool').is(':checked')) {
        var docroot = $('#settings_docroot').val();
      }
      // Add the drupal Version
      site.override_attributes.drupal.sites[site_name].drupal = {
        version: $('#drupal_version').val(),
      }
      // Add settings
      site.override_attributes.drupal.sites[site_name].drupal.settings = {
        files: $('#settings_files').val(),
        settings: {
          default: {
            location: $('#settings_settings').val(),
          }
        }
      };

      // Add the profile
      if ($('input[name="action_install"]').is(':checked')) {
        var profile = $('#settings_profile').val();
        site.override_attributes.drupal.sites[site_name].drupal.settings.profile = profile;
      }

      // Add the db file
      if ($('input[name="action_import"]').is(':checked')) {
        var dbFile = $('#settings_db_file').val();
        site.override_attributes.drupal.sites[site_name].drupal.settings.db_file = '/vagrant/' + dbFile;
      }

      // Add the repository
      if ($('input[name="git_yes"]').is(':checked')) {
        var gitHost = $('#git_host').val();
        var gitRepo = $('#git_repo').val();
        var gitRev = $('#git_rev').val();
        site.override_attributes.drupal.sites[site_name].repository = {
          host: gitHost,
          uri: gitRepo,
          revision: gitRev,
        };
      }
      var jsonFile = null;
      makejsonFile = function (text) {
        var data = new Blob([text], {type: 'text/json'});

        // If we are replacing a previously generated file we need to
        // manually revoke the object URL to avoid memory leaks.
        if (jsonFile !== null) {
          window.URL.revokeObjectURL(jsonFile);
        }

        jsonFile = window.URL.createObjectURL(data);

        return jsonFile;
      };

      var link = document.getElementById('downloadlink');
      link.href = makejsonFile(JSON.stringify(site, null, 2));
      link.download = site_name + '.json';
      link.style.display = 'block';
    }
  });

})(jQuery)
