(function($){
  // We will save multiple sites into local storage
  var sites = JSON.parse(localStorage.getItem('vampd'));
  if (sites == null) {
    var sites = {}
  }
  // Set up a blank object.
  var site = {};

  /**
   * Function to validate form
   * @return true or false if not valid.
   */
  function validateForm() {
    var result = true;
    $('label.required + input[type="text"]').each(function() {
      if ($(this).val() == '') {
        $(this).prev().addClass('error');
        result = false;
      }
      else {
        $(this).prev().removeClass('error');
      }
    });
    return result;
  }

  /**
   * Returns JSON string
   */
  function createSite() {
    // Now we need to check values and start adding them to a json.
    var site_name = $('#site_name').val();
    site.name = site_name;
    site.description = 'This role was generated by the vampd generator';
    site.chef_type = 'role';
    site.json_class = 'Chef::Role';
    site.default_attributes = {};
    site.override_attributes = {
      drupal: {
        sites: {
        }
      }
    };
    site.override_attributes.drupal.sites[site_name] = {};
    site.override_attributes.drupal.sites[site_name].active = true;
    site.override_attributes.drupal.sites[site_name].deploy = {};
    // Add the actions
    var actions = [];
    $('#actions input').each(function(i){
      if ($(this).is(':checked')) {
        actions[i] = $(this).val();
      }
    });
    site.override_attributes.drupal.sites[site_name].deploy.action = actions;
    // Check the docroot
    var docroot = '';
    var docroot_before = '';
    if ($('#docroot_bool').is(':checked')) {
      var docroot = $('#settings_docroot').val();
    }
    // Add the drupal Version
    site.override_attributes.drupal.sites[site_name].drupal = {
      version: $('#drupal_version').val(),
    }
    // Add settings
    site.override_attributes.drupal.sites[site_name].drupal.settings = {
      docroot: docroot,
      files: $('#settings_files').val(),
      settings: {
        default: {
          location: $('#settings_settings').val(),
        }
      }
    };

    // Add the profile
    if ($('#action_install').is(':checked')) {
      var profile = $('#settings_profile').val();
      site.override_attributes.drupal.sites[site_name].drupal.settings.profile = profile;
    }

    // Add the db file
    if ($('#action_import').is(':checked')) {
      var dbFile = $('#settings_db_file').val();
      site.override_attributes.drupal.sites[site_name].drupal.settings.db_file = '/vagrant/' + dbFile;
    }

    // Add the repository
    if ($('#git_bool').is(':checked')) {
      var gitHost = $('#git_host').val();
      var gitRepo = $('#git_repo').val();
      var gitRev = $('#git_rev').val();
      site.override_attributes.drupal.sites[site_name].repository = {
        host: gitHost,
        uri: gitRepo,
        revision: gitRev,
      };
    }

    return site;
  }

  /**
   * Function to create JSON File for download.
   */
  var jsonFile = null;
  function makeJsonFile(json) {
    var data = new Blob([json], {type: 'text/json'});
    // If we are replacing a previously generated file we need to
    // manually revoke the object URL to avoid memory leaks.
    if (jsonFile !== null) {
      window.URL.revokeObjectURL(jsonFile);
    }
    jsonFile = window.URL.createObjectURL(data);
    return jsonFile;
  }

  /**
   * Function to clear the form through refreshing the page
   */
  function clearForm() {
    document.location.reload(true);
  }

  /**
   * Clear the localstored previous projects.
   */
  function clearPreviousSites() {
    var sites = {}
    localStorage.setItem('vampd', JSON.stringify(sites));
  }

  /**
   * Update the form with the preselected values
   */
  function updateForm(site) {
    $('#site_name').val(site.name);
    $.each(site.override_attributes.drupal.sites, function(i) {
      // Loop through the actions and set the form with the defined actions.
      $('#actions input').prop('checked', false);
      $.each(this.deploy.action, function(i) {
        var action = this.toString();
        $('input[name="action_' + action + '"]').click();
      });
      // Load the github
      if (this.repository != null) {
        $('#git_host').val(this.repository.host.toString());
        $('#git_repo').val(this.repository.uri.toString());
        $('#git_rev').val(this.repository.revision.toString());
        $('#git_bool').click();
      }
      // Load the profile
      if (this.drupal.settings.profile != null) {
        $('#settings_profile').val(this.drupal.settings.profile.toString());
      }
      // Load the db_file location.
      if (this.drupal.settings.db_file != null) {
        // Load the string and remove the /vagrant/ we append to it.
        var db_file = this.drupal.settings. db_file.toString().substring(9)
        $('#settings_db_file').val(db_file);
      }
      // Load the docroot
      if (this.drupal.settings.docroot != null) {
        $('#settings_docroot').val(this.drupal.settings.docroot.toString())
        $('#docroot_bool').click();
      }
      // Load the files
      $('#settings_files').val(this.drupal.settings.files.toString());
      // Load the default settings.php location.
      $('#settings_settings').val(this.drupal.settings.settings.default.location.toString());
    });
  }

  /**
   * Function to Update live text area
   * @param  {[type]} e) {               e.preventDefault();    var validate [description]
   * @return {[type]}    [description]
   */
  function updateLiveJson(site) {
    $('#live-output .site-name b').html(site.name + '.json');
    var jsonString = JSON.stringify(site, null, 2);
    $('#live-output textarea').html(jsonString);
  }

  $('#submit').on('click', function(e) {
    e.preventDefault();
    var validate = validateForm();
    if (validate) {
      var site = createSite();
      var link = document.getElementById('downloadlink');
      link.href = makeJsonFile(JSON.stringify(site, null, 2));
      link.download = site.name + '.json';
      link.style.display = 'block';
      sites[site.name] = site;
      // Save the site to local storage.
      localStorage.setItem('vampd', JSON.stringify(sites));
    }
  });

  // Update the site text area.
  $('#site_1').on('change', function(e) {
    var validate = validateForm();
    if (validate) {
      createSite();
      updateLiveJson(site);
    }
  });

  $('input[type="text"]').on('keypress', function(e) {
    var validate = validateForm();
    if (validate) {
      createSite();
      updateLiveJson(site);
    }
  });
  // Loop through the sites, and set the options.
  $.each(sites, function(i) {
    var site_name  = this.name;
    $('#previous_sites').prepend('<option value="' + site_name + '">' + site_name + '</option>');
  });

  // On the change of previous sites, we want to autofill the form
  $('#previous_sites').on('change', function(e) {
    var site_name = $(this).val();
    site = sites[site_name];
    if (site_name !== '_none') {
      updateForm(site);
    }
    else {
      clearForm(site);
    }
  });

  // Clear Sites
  $('#clear_sites').on('click', function(e) {
    e.preventDefault();
    if (confirm('Are you sure you want to remove all previously stored sites?')){
      clearPreviousSites();
      clearForm();
    }
  });

})(jQuery)
